### ISSUE TITLE
Discrepancy between getNormalizedArray & getClosestWebColor

### ISSUE THREAD

**Issue by micschk** [tecnickcom/tc-lib-color#4]
The array returned by getNormalizedArray contains R,G,B,A keys while getClosestWebColor expects them to be 'red', 'green', 'blue'.

**Comment by nicolaasuni** [comment]
When the keys are in long form (i.e. 'red', 'green', 'blue'), then the values are expected to be in the range between 0 and 1 (float numbers).
The short single-letter keys indicate a normalized value between 0 and $max (i.e. between 0 and 255).

The getNormalizedArray method should be used only when you need a normalized value indeed. This is typically at the end of calculations, just before printing the output in a web page for instance.
