### ISSUE TITLE
getClosestWebColor never seems to return anything

### ISSUE THREAD

**Issue by micschk** [tecnickcom/tc-lib-color#5]
Starting from a hex formatted color '#77675b':
```php
        $colorHelper = new \Com\Tecnick\Color\Web();

        $colorObj = $colorHelper->getRgbObjFromHex($hex);
        $webRgbaArr = $colorObj->getNormalizedArray(255);

        $renamedWebRgbArr = ['red' => $webRgbaArr['R'], 'green' => $webRgbaArr['G'], 'blue' => $webRgbaArr['B']];
        $webColorName = $colorHelper->getClosestWebColor($renamedWebRgbArr);

        var_dump($hex);
        var_dump($renamedWebRgbArr);
        var_dump($webColorName);
```
Results in:
```
string(7) "#77675b"
array(3) {
  ["red"]=>
  float(119)
  ["green"]=>
  float(103)
  ["blue"]=>
  float(91)
}
string(0) ""
``

**Comment by nicolaasuni** [comment]
As explained in https://github.com/tecnickcom/tc-lib-color/issues/4 When the keys are in long form (i.e. 'red', 'green', 'blue'), then the values are expected to be in the range between 0 and 1 (float numbers).
The short single-letter keys indicate a normalized value between 0 and $max (i.e. between 0 and 255).

This should be clear from the method test:
https://github.com/tecnickcom/tc-lib-color/blob/develop/test/WebTest.php#L191

To prepare the input for getClosestWebColor() you can use toRgbArray() as in the following example:
https://github.com/tecnickcom/tc-lib-color/blob/develop/example/index.php#L47
