### ISSUE TITLE
Some methods could probably better be static

### ISSUE THREAD

**Issue by micschk** [tecnickcom/tc-lib-color#6]
For exampe:
- Web::getClosestWebColor
- Web::getNameFromHex
- Web::extractHexCode
- ...

Actually, all of the methods in Web seem to be working with arguments, none of them depend on an instantiated object ($this)?

**Comment by nicolaasuni** [comment]
Generally speaking, static methods break a lot of the power available to Object-Oriented code and make harder to perform unit testing.
A lot has been written on this subject, a web search should give you more details ...
